#! /usr/bin/python
import pygtk
pygtk.require('2.0')
import gtk
import os
import sys

def copy_image(f):
    assert os.path.exists(f), "No such file."
    image = gtk.gdk.pixbuf_new_from_file(f)

    clip = gtk.clipboard_get()
    clip.set_image(image)
    clip.store()

copy_image(sys.argv[1]);
